<dl>
    <img src="views/layout/default/img/logo.jpg" alt="UNIR" id="logo-unir" /> 
    <h1>Aplicación web para liquidar procedimientos médicos, quirúrgicos y hospitalarios en Colombia</h1>
    <h2>Máster universitario en Ingeniería de Software y Sistemas Informáticos</h2>
    <h3>Tarifarios:
        <dd>
            <ul> 
                <li type="circle">SOAT</li>
                <li type="circle">ISS 256 - 2001</li>
                <li type="circle">ISS 312 - 2004</li>
            </ul>
        </dd>
    </h3>
</dl>